title: Download and Install Wireless Canon Printer 
description: <a href="http://canoncom.ijsetup.s3-website-us-west-1.amazonaws.com"><img src="/Get-Started-Now-Button3.png"alt="Canon.com/ijsetup"/></a>

theme: jekyll-theme-cayman